version: 0.1

phases:
  build:
    commands:
       - echo Build started on `date`
       - ./gradlew build
  post_build:
    commands:
       - echo Build completed on `date`
       - cd build/libs
       - zip -r lab1-git-race.zip ./*.war
artifacts:
  files:
    - 'build/libs/lab1-git-race.zip'
  discard-paths: yes
