version: 0.1

phases:
  build:
    commands:
       - echo Build started on `date`
       - ./gradlew build
  post_build:
    commands:
       - echo Build completed on `date`
       - zip -r -j lab1-git-race.zip 'build/libs' -i '/*.war'
artifacts:
  files:
    - 'lab1-git-race.zip'
  discard-paths: yes
